language: cpp
compiler:
  - gcc
  - clang
script:
  - make test
  - $CXX -o cppcheck -O2 cli/*.cpp lib/*.cpp -Ilib
  - ./cppcheck --error-exitcode=1 --enable=style --suppress=duplicateBranch --suppress=stlIfStrFind -q cli gui lib -igui/test
