language: cpp
compiler:
  - gcc
  - clang
script:
  - mkdir build
  - make test SRCDIR=build VERIFY=1
  - ./cppcheck --error-exitcode=1 -Ilib --enable=style --suppress=duplicateBranch cli gui lib -igui/test
  - sudo apt-get update
  - sudo apt-get install python-pygments
  - ./htmlreport/test_htmlreport.py
  - cd htmlreport
  - ./cppcheck-htmlreport --file ../gui/test/data/xmlfiles/xmlreport_v1.xml --title "this is a test" --report-dir . --source-dir ../test/
  - ./cppcheck-htmlreport --file ../gui/test/data/xmlfiles/xmlreport_v2.xml --title "this is a test" --report-dir . --source-dir ../test/
  - cd ../
notifications:
  irc:
    channels:
      - "irc.freenode.org#cppcheck"
    template:
      - "[%{commit} : %{author}] %{message}"
      - "%{build_url}"
    skip_join: true

