version: 1.69.{build}

environment:
- VisualStudioVersion: 11.0
- VisualStudioVersion: 12.0

configuration:
- Debug
- Release

platform:
- Win32
- x64

build_script:
- msbuild "cppcheck.sln" /m /verbosity:minimal

test_script:
- if "%CONFIGURATION%" == "Release" bin\testrunner.exe
- if "%CONFIGURATION%" == "Debug"   bin\debug\testrunner.exe
